### ISSUE TITLE
Unavailable mosque error!

### ISSUE THREAD

**Issue by FirasTelmoudi** [mawaqit/android-tv-app#1165] opened 2024-05-30 13:18 UTC
**Describe the bug**
Sometimes this screen pops up out of nowhere the mosque staff have to close the app and re open it to get it back to normal
This happens in mosque ID 19466

**To Reproduce**
Happens suddenly 

**Expected behavior**
Should show the mosque main screen instead 

**Screenshots**
![image](https://github.com/mawaqit/android-tv-app/assets/29250587/1e95e55a-24d0-4e43-9935-3f86883f9ef4)

**Android TV/Box (please complete the following information):**
 - Device: android smart tv
 - OS: Android 10
 - Version mawaqit latest version 1.10.1-340

**Additional context**
I'm here if you need any troubleshooting and i hope you adresse this issues asap
Thank you

**Comment by ibrahim-zehhaf-mawaqit** [comment] 2024-07-11 08:25
Salam alaykum 
Can you test the last version 1.11.0 please and tel us if the issue is still present

**Comment by ibrahim-zehhaf-mawaqit** [comment] 2024-07-11 08:42
Thanks, I m closing the issue, feel free to reopen it if the pb is back

**Closed by ibrahim-zehhaf-mawaqit** 2024-07-11 08:42 UTC
Labels: bug
